OptimizeSpatial table function improvements
CartoDB/analytics-toolbox-databricks pull request #15
Opened 2022-04-26 21:56 UTC by moradology

This PR addresses the improvements described in #12

2022-04-27 14:34 UTC, pomadchin requested changes
That's a good move, I like the idea of determining the column type, however the code requires some significant corrections and testing.

2022-04-27 14:34 UTC, pomadchin commented on core/src/main/scala/com/carto/analyticstoolbox/spark/spatial/OptimizeSpatial.scala
> +      if (table_df.schema(geomColumn).dataType == "binary") "ST_geomFromTWKB"
If it's binary, it's already a geom, see https://github.com/CartoDB/analytics-toolbox-databricks/blob/main/core/src/main/scala/com/carto/analyticstoolbox/core/package.scala#L32-L38

So `Geometry` is represented by the binary type already.

2022-04-27 14:34 UTC, pomadchin commented on core/src/main/scala/com/carto/analyticstoolbox/spark/spatial/OptimizeSpatial.scala
> +    val table_df = ssc.table(sourceTable)
the style is not too important for sure, but underscores is a py thing :D
how about just `df`?

2022-04-27 14:34 UTC, pomadchin commented on core/src/main/scala/com/carto/analyticstoolbox/spark/spatial/OptimizeSpatial.scala
> +      if (table_df.schema(geomColumn).dataType == "binary") "ST_geomFromTWKB"
`table_df.schema(geomColumn).dataType` returns an object of the `DataType` type, => `table_df.schema(geomColumn).dataType == "binary"` should always be `false`; 

```scala
import org.apache.spark.sql.types.BinaryType

if (table_df.schema(geomColumn).dataType == BinaryType) ....
```

should do the thing.

2022-04-27 14:34 UTC, pomadchin commented on core/src/main/scala/com/carto/analyticstoolbox/spark/sql/SpatialFilterPushdownOptimizations.scala
> +  }
I believe it is a test code? should it be removed?

2022-04-27 14:34 UTC, pomadchin commented on core/src/main/scala/com/carto/analyticstoolbox/spark/sql/SpatialFilterPushdownOptimizations.scala
> +    writeFile("/databricks/test", "NOW INITIATING OPTIMIZATIONS")
the same about these lines

2022-04-27 14:34 UTC, pomadchin commented on core/src/main/scala/com/carto/analyticstoolbox/spark/sql/rules/SpatialFilterPushdownRules.scala
> +
The test code?

2022-04-27 14:34 UTC, pomadchin commented on core/src/main/scala/com/carto/analyticstoolbox/spark/sql/rules/SpatialFilterPushdownRules.scala
> +              WriteFile("/databricks/testrules", "testing...")
These test lines actually break tests.

2022-04-27 14:34 UTC, pomadchin commented on core/src/main/scala/com/carto/analyticstoolbox/spark/spatial/OptimizeSpatial.scala
> -         |      geom AS wkt,
wkt column is not used.

2022-04-27 14:34 UTC, pomadchin commented on core/src/main/scala/com/carto/analyticstoolbox/spark/spatial/OptimizeSpatial.scala
> -         |      st_partitionCentroid(geom, $zoom) AS partitioning
I think I had to clarify the original idea here:

* Remove all unused columns from the *result table*

The result table is the parquet table, we need some columns to partition the table, but we don't need them to query data.

All these columns are used to shape a proper table partitioing. That's how it should look like after this PR:

```scala
""" CREATE TEMPORARY VIEW ${sourceTable}_idx_view AS(
         |  WITH orig_q AS (
         |    SELECT
         |      * EXCEPT($geomColumn),
         |      $parseGeom($geomColumn) AS geom
         |      FROM $sourceTable
         |    )
         |    SELECT
         |      *,
         |      st_z2LatLon(geom) AS __carto_z2,
         |      st_extentFromGeom(geom) AS __carto_index,
         |      st_partitionCentroid(geom, $zoom) AS __carto_partitioning
         |      FROM orig_q
         |      DISTRIBUTE BY __carto_partitioning SORT BY __carto_z2.min, __carto_z2.max
         |  );
```

These lines (https://github.com/CartoDB/analytics-toolbox-databricks/blob/main/core/src/main/scala/com/carto/analyticstoolbox/spark/spatial/OptimizeSpatial.scala#L80-L86) should be changed to: 

```scala
    ssc.sql(
      s"""
         |CREATE TABLE $outputTable
         |USING PARQUET LOCATION '$outputLocation/$outputTable'
         |AS (SELECT * EXCEPT (__carto_partitioning,  __carto_z2) FROM ${sourceTable}_idx_view);
         |""".stripMargin
    )
```

2022-04-27 14:48 UTC, moradology commented on core/src/main/scala/com/carto/analyticstoolbox/spark/spatial/OptimizeSpatial.scala
> +    val table_df = ssc.table(sourceTable)
Oof. Too much recent python

2022-04-27 14:48 UTC, moradology commented on core/src/main/scala/com/carto/analyticstoolbox/spark/spatial/OptimizeSpatial.scala
> +      if (table_df.schema(geomColumn).dataType == "binary") "ST_geomFromTWKB"
My quick test of this must've worked as a result of falling back on `else` 🤦

2022-04-28 14:02 UTC, pomadchin requested changes
LGTM! I have two questions: 
- was it tested on a DB cluster? 
- how to force the blocksize in case we don't want it's auto computation?

2022-04-28 14:02 UTC, pomadchin commented on core/src/main/scala/com/carto/analyticstoolbox/spark/spatial/OptimizeSpatial.scala
> +    geomColumn: String
I would move it into the position before zoom 🤷

2022-04-28 14:02 UTC, pomadchin commented on core/src/main/scala/com/carto/analyticstoolbox/spark/spatial/OptimizeSpatial.scala
> +      if (df.schema(geomColumn).dataType == BinaryType) ""
Did you have a chance to test it?

2022-04-28 14:02 UTC, pomadchin commented on core/src/main/scala/com/carto/analyticstoolbox/spark/spatial/package.scala
> +      blockSizeDefault: Int = 2097000,
How to use this function in case I want to force the fixed blocksize myself?

2022-04-28 14:04 UTC, pomadchin commented on core/src/main/scala/com/carto/analyticstoolbox/spark/spatial/OptimizeSpatial.scala
> +         |      DISTRIBUTE BY __carto_partitioning SORT BY __carto_z2.min, __carto_z2.max
These changes are not affected in the `blockSizeCompute` function: https://github.com/CartoDB/analytics-toolbox-databricks/blob/7976ef8d6f276e55f21d45b39371994b6d187b1e/core/src/main/scala/com/carto/analyticstoolbox/spark/spatial/OptimizeSpatial.scala#L120-L125

2022-04-28 14:18 UTC, moradology commented on core/src/main/scala/com/carto/analyticstoolbox/spark/spatial/OptimizeSpatial.scala
> +      if (df.schema(geomColumn).dataType == BinaryType) ""
I did, but i should run it again as i've since changed the source

2022-04-28 16:29 UTC, pomadchin approved these changes
🚀 Let's wait for the DB cluster tests and than merge it!

2022-04-28 17:15 UTC, merged